caps:
  platformName: "Android"
  platformVersion: "6.0.1"
  deviceName: "emulator-5554"
  appPackage: "com.tencent.wework"
  appActivity: ".launch.LaunchSplashActivity"
  noReset: "True"

server:
  ip: "localhost"
  port: "4723"