caps:
  platformName: "Android"
  platformVersion: "6.0.1"
  deviceName: "emulator-5554"
  appPackage: "com.xueqiu.android"
  appActivity: ".view.WelcomeActivityAlias"
  noReset: "True"

server:
  ip: "localhost"
  port: "4723"